package com.cg.pecuniabank.dto;


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name="Account")
public class AccountDetails {
	//Our customer has only one account in our bank.
	//Every customer of our bank get unique customer id generated by bank.
	@Id
	@Column(name="Account_Number") //may be generate by employee or auto generate by any service.
	String accountNumber;
	@Column(name="Account_Balance")
	String accountBalance;
	@Column(name="Account_Holder_Name")//customer name
	String accountHolderName;
	@Column(name="Currency")//by default INR
	String currency;
	@Column(name="Credit_Score") //It is auto generated but now employee fill the credit score by it own.
	String creditScore;
	@OneToOne(cascade=CascadeType.ALL)   // 1:1 unidirectional
	@JoinColumn(name="Customer_Id")
	CustomerDetails customerDetails;
	@ManyToOne(optional = false)  // N:1 unidirectional 
	@JoinColumn(name="Branch_Id")  //We use optional is false it means by default every Account holder get same branch details.
	BranchDetails branchdetails;
	
	
	
}
