package com.cg.pecuniabank.dto;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name="Customer")
public class CustomerDetails {
	//A hard copy of from to fill customer details.
	//Verified the customer details.(Official tools to verified the details that is mention by the customer and insert by the employee .
	//After verification the provide the Customer id , Account Number and other details is generated by bank. 
	
	@Id
	@Column(name="Customer_ID")
	String customerID;      //by default it written in the form.
	@Column(name="Customer_First_Name")
	String customerFirstName;
	@Column(name="Customer_Last_Name")
	String customerLastName;
	@Column(name="DOB")
	String DOB;//date of birth format like (day/Mon/Year)
	@Column(name="Age")
	String age;
	public String getCustomerID() {
		return customerID;
	}
	public void setCustomerID(String customerID) {
		this.customerID = customerID;
	}
	public String getCustomerFirstName() {
		return customerFirstName;
	}
	public void setCustomerFirstName(String customerFirstName) {
		this.customerFirstName = customerFirstName;
	}
	public String getCustomerLastName() {
		return customerLastName;
	}
	public void setCustomerLastName(String customerLastName) {
		this.customerLastName = customerLastName;
	}
	public String getDOB() {
		return DOB;
	}
	public void setDOB(String dOB) {
		DOB = dOB;
	}
	public String getAge() {
		return age;
	}
	public void setAge(String age) {
		this.age = age;
	}
	public String getPanNumber() {
		return panNumber;
	}
	public void setPanNumber(String panNumber) {
		this.panNumber = panNumber;
	}
	public String getAdharNumber() {
		return adharNumber;
	}
	public void setAdharNumber(String adharNumber) {
		this.adharNumber = adharNumber;
	}
	public String getAccountType() {
		return accountType;
	}
	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}
	public String getOpeningBalance() {
		return openingBalance;
	}
	public void setOpeningBalance(String openingBalance) {
		this.openingBalance = openingBalance;
	}
//	public Address getAddress() {
//		return Address;
//	}
//	public void setAddress(Address address) {
//		Address = address;
//	}
	@Column(name="Pan_Number")
	String panNumber;
	@Column(name="Adhar_Number")
	String adharNumber;
	@Column(name="Account_Type") // saving or current
	String accountType;
	@Column(name="Opening_Balance") //Minimum balance required to open the bank;(5000/-)
	String openingBalance;
//	@OneToOne(cascade=CascadeType.ALL)   // 1:1 unidirectional
//	@JoinColumn(name="address_id")
//	Address Address;
//	

}
